#!/bin/bash

yes_NO() {
  read -rp "$1 [y/N] " R && [[ $R == [yY] || $R == [yY][eE][sS] ]] || exit 1
}

browser() {
  chromium --remote-debugging-port=21222 &>/dev/null
}

if [ ! "$(ss -tuna | grep 21222)" ]; then
  yes_NO "close chromium?"
  pkill chromium
  browser &
  sleep 2
fi

bun ~/brow/index.js "$1"
